#!/usr/bin/env bash
set -euo pipefail

RPGK_REPO="${RPGK_REPO:-Shashakar/RPG-Kingdom}"
TOKEN="${SYMPHONY_GITHUB_TOKEN:-}"
MARKER="${RPGK_ATTEMPT_MARKER:-.symphony-attempt-complete}"
CONTEXT_FILE="${RPGK_CONTINUATION_CONTEXT_FILE:-.symphony-continuation-context.md}"

workspace_name="$(basename "$PWD")"
if [[ ! "$workspace_name" =~ ^GH-([0-9]+)$ ]]; then
  rm -f -- "$CONTEXT_FILE"
  exit 0
fi
issue_number="${BASH_REMATCH[1]}"

# Fresh issues do not need continuation context. Remove any stale file from a recycled workspace.
if [[ ! -f "$MARKER" ]]; then
  rm -f -- "$CONTEXT_FILE"
  exit 0
fi

if [[ -z "$TOKEN" ]]; then
  echo "RPG Kingdom continuation context: SYMPHONY_GITHUB_TOKEN is required for reviewed continuation context" >&2
  exit 73
fi

marker_timestamp="$(sed -n 's/^completed worker lifetime for GH-[0-9][0-9]* at //p' "$MARKER" | tail -n 1)"
if [[ -z "$marker_timestamp" ]]; then
  echo "RPG Kingdom continuation context: could not parse prior attempt timestamp from $MARKER" >&2
  exit 73
fi

branch="$(git branch --show-current 2>/dev/null || true)"
repo_owner="${RPGK_REPO%%/*}"
repo_name="${RPGK_REPO#*/}"

# Keep the host-generated context local to the workspace. It is orchestration state, not source.
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  exclude_file="$(git rev-parse --git-path info/exclude)"
  mkdir -p "$(dirname "$exclude_file")"
  touch "$exclude_file"
  exclude_pattern="/${CONTEXT_FILE#./}"
  if ! grep -Fxq -- "$exclude_pattern" "$exclude_file"; then
    printf '%s\n' "$exclude_pattern" >> "$exclude_file"
  fi
fi

api() {
  GH_TOKEN="$TOKEN" gh api "$@"
}

issue_comments="$(api "repos/$RPGK_REPO/issues/$issue_number/comments?per_page=100")"

pr_json='[]'
if [[ -n "$branch" ]]; then
  encoded_branch="$(jq -rn --arg value "$branch" '$value|@uri')"
  pr_json="$(api "repos/$RPGK_REPO/pulls?state=open&head=$repo_owner:$encoded_branch&per_page=10")"
fi

pr_number="$(jq -r '.[0].number // empty' <<<"$pr_json")"
pr_title="$(jq -r '.[0].title // empty' <<<"$pr_json")"
pr_url="$(jq -r '.[0].html_url // empty' <<<"$pr_json")"
pr_head_sha="$(jq -r '.[0].head.sha // empty' <<<"$pr_json")"
pr_body="$(jq -r '.[0].body // empty' <<<"$pr_json")"

reviews='[]'
review_threads='{"data":{"repository":{"pullRequest":{"reviewThreads":{"nodes":[]}}}}}'
pr_comments='[]'
if [[ -n "$pr_number" ]]; then
  reviews="$(api "repos/$RPGK_REPO/pulls/$pr_number/reviews?per_page=100")"
  pr_comments="$(api "repos/$RPGK_REPO/issues/$pr_number/comments?per_page=100")"
  review_threads="$(GH_TOKEN="$TOKEN" gh api graphql \
    -f query='query($owner:String!,$name:String!,$number:Int!){repository(owner:$owner,name:$name){pullRequest(number:$number){reviewThreads(first:100){nodes{isResolved comments(first:20){nodes{author{login} body createdAt url}}}}}}}' \
    -f owner="$repo_owner" \
    -f name="$repo_name" \
    -F number="$pr_number")"
fi

{
  printf '# Symphony reviewed continuation context\n\n'
  printf 'This file is generated by the Supervisor host for a rearmed worker lifetime. Treat current unresolved review feedback and newer continuation comments as required context in addition to the original issue description. Do not infer that the original acceptance criteria alone are sufficient when this file contains newer review requirements.\n\n'
  printf -- '- Issue: GH-%s\n' "$issue_number"
  printf -- '- Previous worker completed: %s\n' "$marker_timestamp"
  printf -- '- Current workspace branch: %s\n' "${branch:-unknown}"

  if [[ -n "$pr_number" ]]; then
    printf '\n## Existing pull request\n\n'
    printf -- '- PR: #%s — %s\n' "$pr_number" "$pr_title"
    printf -- '- URL: %s\n' "$pr_url"
    printf -- '- Current head: `%s`\n' "$pr_head_sha"
    if [[ -n "$pr_body" ]]; then
      printf '\n### Current PR description\n\n%s\n' "$pr_body"
    fi

    printf '\n## Current review submissions\n\n'
    if jq -e '[.[] | select((.body // "") != "")] | length > 0' >/dev/null <<<"$reviews"; then
      jq -r '.[] | select((.body // "") != "") | "### " + (.state // "REVIEW") + " by " + (.user.login // "unknown") + "\n\n" + .body + "\n"' <<<"$reviews"
    else
      printf 'No review submission bodies are currently present.\n'
    fi

    printf '\n## Unresolved inline review threads\n\n'
    if jq -e '[.data.repository.pullRequest.reviewThreads.nodes[]? | select(.isResolved == false)] | length > 0' >/dev/null <<<"$review_threads"; then
      jq -r '.data.repository.pullRequest.reviewThreads.nodes[]? | select(.isResolved == false) | .comments.nodes[]? | "### " + (.author.login // "unknown") + "\n" + (.url // "") + "\n\n" + (.body // "") + "\n"' <<<"$review_threads"
    else
      printf 'No unresolved inline review threads are currently present.\n'
    fi

    printf '\n## New PR conversation comments since the previous worker\n\n'
    if jq -e --arg ts "$marker_timestamp" '[.[] | select(.created_at > $ts)] | length > 0' >/dev/null <<<"$pr_comments"; then
      jq -r --arg ts "$marker_timestamp" '.[] | select(.created_at > $ts) | "### " + (.user.login // "unknown") + " — " + .created_at + "\n\n" + (.body // "") + "\n"' <<<"$pr_comments"
    else
      printf 'No newer PR conversation comments.\n'
    fi
  else
    printf '\n## Existing pull request\n\nNo open PR was found for the current workspace branch.\n'
  fi

  printf '\n## New issue comments since the previous worker\n\n'
  if jq -e --arg ts "$marker_timestamp" '[.[] | select(.created_at > $ts)] | length > 0' >/dev/null <<<"$issue_comments"; then
    jq -r --arg ts "$marker_timestamp" '.[] | select(.created_at > $ts) | "### " + (.user.login // "unknown") + " — " + .created_at + "\n\n" + (.body // "") + "\n"' <<<"$issue_comments"
  else
    printf 'No newer issue comments.\n'
  fi
} > "$CONTEXT_FILE"

echo "RPG Kingdom continuation context: wrote $CONTEXT_FILE for GH-$issue_number${pr_number:+ / PR #$pr_number}" >&2
